In [1]:
try:
    from openmdao.utils.notebook_utils import notebook_mode
except ImportError:
    !python -m pip install openmdao[notebooks]

# Changing Check Settings for FD or CS

## Changing Settings for Inputs on a Specific Component

You can change the settings for the approximation schemes that will be used to compare with your component’s derivatives by calling the `set_check_partial_options` method.

```{eval-rst}
    .. automethod:: openmdao.core.component.Component.set_check_partial_options
        :noindex:
```

```{Note}
If you want to use method=”cs”, then you must also pass `force_alloc_complex`=True to setup. See the example below.
``` 

This allows custom tailoring of the approximation settings on a variable basis.

## Usage Examples

In [2]:
from openmdao.utils.notebook_utils import get_code
from myst_nb import glue
glue("code_src59", get_code("openmdao.test_suite.components.paraboloid_mat_vec.ParaboloidMatVec"), display=False)

:::{Admonition} `ParaboloidMatVec` class definition 
:class: dropdown

{glue:}`code_src59`
:::

In [3]:
from openmdao.utils.notebook_utils import get_code
from myst_nb import glue
glue("code_src60", get_code("openmdao.core.tests.test_check_partials.ParaboloidTricky"), display=False)

:::{Admonition} `ParaboloidTricky` class definition 
:class: dropdown

{glue:}`code_src60`
:::

In [4]:
import openmdao.api as om
from openmdao.core.tests.test_check_partials import ParaboloidTricky
from openmdao.test_suite.components.paraboloid_mat_vec import ParaboloidMatVec

prob = om.Problem()

comp = prob.model.add_subsystem('comp', ParaboloidTricky())
prob.model.add_subsystem('comp2', ParaboloidMatVec())

prob.model.connect('comp.f_xy', 'comp2.x')

prob.set_solver_print(level=0)

comp.set_check_partial_options(wrt='*', step=1e-2)

prob.setup()
prob.run_model()

prob.check_partials(compact_print=True)

----------------------------------
Component: ParaboloidTricky 'comp'
----------------------------------

+-----------------+------------------+-------------+----------+-------------+-------------+------------+------------+-------------+------------+------------+------------+
| of '<variable>' | wrt '<variable>' |    fwd mag. | rev mag. |  check mag. |  a(fwd-chk) | a(rev-chk) | a(fwd-rev) |  r(fwd-chk) | r(rev-chk) | r(fwd-rev) | error desc |
+=================+==================+=============+==========+=============+=============+============+============+=============+============+============+============+
| 'f_xy'          | 'x'              |  6.0000e-07 | n/a      |  6.0000e-07 |  4.9644e-14 | n/a        | n/a        |  8.2740e-08 | n/a        | n/a        |            |
+-----------------+------------------+-------------+----------+-------------+-------------+------------+------------+-------------+------------+------------+------------+
| 'f_xy'          | 'y'              | 

{'comp': {('f_xy', 'x'): {'J_fwd': array([[-6.e-07]]),
   'J_fd': array([[-6.0000005e-07]]),
   'abs error': ErrorTuple(forward=4.964422262660536e-14, reverse=None, forward_reverse=None),
   'rel error': ErrorTuple(forward=8.274036419837383e-08, reverse=None, forward_reverse=None),
   'magnitude': MagnitudeTuple(forward=6e-07, reverse=None, fd=6.000000496442226e-07)},
  ('f_xy', 'y'): {'J_fwd': array([[8.e-07]]),
   'J_fd': array([[8.00000066e-07]]),
   'abs error': ErrorTuple(forward=6.619229683547381e-14, reverse=None, forward_reverse=None),
   'rel error': ErrorTuple(forward=8.274036419837383e-08, reverse=None, forward_reverse=None),
   'magnitude': MagnitudeTuple(forward=8e-07, reverse=None, fd=8.000000661922968e-07)}},
 'comp2': {('f_xy', 'x'): {'J_fwd': array([[38.]]),
   'J_rev': array([[38.]]),
   'J_fd': array([[38.00000104]]),
   'abs error': ErrorTuple(forward=1.0409276001155376e-06, reverse=1.0409276001155376e-06, forward_reverse=0.0),
   'rel error': ErrorTuple(forward=2.7

Here, we show how to set the method. In this case, we use complex step on TrickyParaboloid because the finite difference is less accurate.

---

```{Note}
You need to `set force_alloc_complex` to True during setup to utilize complex step during a check.
```

In [5]:
import openmdao.api as om
from openmdao.core.tests.test_check_partials import ParaboloidTricky
from openmdao.test_suite.components.paraboloid_mat_vec import ParaboloidMatVec

prob = om.Problem()

comp = prob.model.add_subsystem('comp', ParaboloidTricky())
prob.model.add_subsystem('comp2', ParaboloidMatVec())

prob.model.connect('comp.f_xy', 'comp2.x')

prob.set_solver_print(level=0)

comp.set_check_partial_options(wrt='*', method='cs')

prob.setup(force_alloc_complex=True)
prob.run_model()

prob.check_partials(compact_print=True)

----------------------------------
Component: ParaboloidTricky 'comp'
----------------------------------

+-----------------+------------------+-------------+----------+-------------+-------------+------------+------------+-------------+------------+------------+------------+
| of '<variable>' | wrt '<variable>' |    fwd mag. | rev mag. |  check mag. |  a(fwd-chk) | a(rev-chk) | a(fwd-rev) |  r(fwd-chk) | r(rev-chk) | r(fwd-rev) | error desc |
+=================+==================+=============+==========+=============+=============+============+============+=============+============+============+============+
| 'f_xy'          | 'x'              |  6.0000e-07 | n/a      |  6.0000e-07 |  0.0000e+00 | n/a        | n/a        |  0.0000e+00 | n/a        | n/a        |            |
+-----------------+------------------+-------------+----------+-------------+-------------+------------+------------+-------------+------------+------------+------------+
| 'f_xy'          | 'y'              | 

{'comp': {('f_xy', 'x'): {'J_fwd': array([[-6.e-07]]),
   'J_fd': array([[-6.e-07]]),
   'abs error': ErrorTuple(forward=0.0, reverse=None, forward_reverse=None),
   'rel error': ErrorTuple(forward=0.0, reverse=None, forward_reverse=None),
   'magnitude': MagnitudeTuple(forward=6e-07, reverse=None, fd=6e-07)},
  ('f_xy', 'y'): {'J_fwd': array([[8.e-07]]),
   'J_fd': array([[8.e-07]]),
   'abs error': ErrorTuple(forward=1.0587911840678754e-22, reverse=None, forward_reverse=None),
   'rel error': ErrorTuple(forward=1.3234889800848445e-16, reverse=None, forward_reverse=None),
   'magnitude': MagnitudeTuple(forward=8e-07, reverse=None, fd=7.999999999999999e-07)}},
 'comp2': {('f_xy', 'x'): {'J_fwd': array([[38.]]),
   'J_rev': array([[38.]]),
   'J_fd': array([[38.00000104]]),
   'abs error': ErrorTuple(forward=1.0409276001155376e-06, reverse=1.0409276001155376e-06, forward_reverse=0.0),
   'rel error': ErrorTuple(forward=2.739283083162063e-08, reverse=2.739283083162063e-08, forward_revers

## Directional Derivatives
You can also specify that an input or set of inputs be checked using a directional derivative. For vector inputs, this means that, instead of calculating the derivative with respect to each element of the array, we calculate the derivative with respect to a linear combination of all array indices. For finite difference and complex step, the step value is applied simultaneously to all elements of the vector. This is a much quicker check because it only requires a single execution of the component for the variable rather than one for each element of the array.

In [6]:
from openmdao.utils.notebook_utils import get_code
from myst_nb import glue
glue("code_src61", get_code("openmdao.test_suite.components.array_comp.ArrayComp"), display=False)

:::{Admonition} `ArrayComp` class definition 
:class: dropdown

{glue:}`code_src61`
:::

In [7]:
import openmdao.api as om
from openmdao.test_suite.components.array_comp import ArrayComp

prob = om.Problem()
model = prob.model
mycomp = model.add_subsystem('mycomp', ArrayComp(), promotes=['*'])

prob.setup()
prob.run_model()

data = prob.check_partials()

-----------------------------
Component: ArrayComp 'mycomp'
-----------------------------

  mycomp: 'y1' wrt 'bb'
     Forward Magnitude: 1.640884e+01
          Fd Magnitude: 1.640884e+01 (fd:forward)

    Absolute Error (Jfor - Jfd) : 0.000000e+00

    Relative Error (Jfor - Jfd) / Jfd : 0.000000e+00

    Raw Forward Derivative (Jfor)
    [[ 1.   6.  -1.   1. ]
     [ 3.   2.5  0.   4. ]
     [-2.   2.   8.  -5. ]
     [ 7.   4.   1.   6. ]]

    Raw FD Derivative (Jfd)
    [[ 1.   6.  -1.   1. ]
     [ 3.   2.5  0.   4. ]
     [-2.   2.   8.  -5. ]
     [ 7.   4.   1.   6. ]]

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  mycomp: 'y1' wrt (d)'x1'
     Forward Magnitude: 1.978004e+01
          Fd Magnitude: 1.978004e+01 (fd:forward)



    Directional Derivative (Jfor)
    [[ 9. ]
     [14.5]
     [ 8. ]
     [ 6. ]]

    Directional FD Derivative (Jfd)
    [[ 9. ]
 [14.5]
 [ 8. ]
 [ 6. ]]

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  mycomp: 'y1' w

If your component is matrix-free and you request directional derivatives, then your reverse mode derivatives will be verified using the dot product test described [here](http://www.reproducibility.org/RSF/book/gee/ajt/paper_html/node20.html).

In [8]:
import numpy as np

import openmdao.api as om

class ArrayCompMatrixFree(om.ExplicitComponent):

    def setup(self):

        J1 = np.array([[1.0, 3.0, -2.0, 7.0],
                        [6.0, 2.5, 2.0, 4.0],
                        [-1.0, 0.0, 8.0, 1.0],
                        [1.0, 4.0, -5.0, 6.0]])

        self.J1 = J1
        self.J2 = J1 * 3.3
        self.Jb = J1.T

        # Inputs
        self.add_input('x1', np.zeros([4]))
        self.add_input('x2', np.zeros([4]))
        self.add_input('bb', np.zeros([4]))

        # Outputs
        self.add_output('y1', np.zeros([4]))

        self.set_check_partial_options('*', directional=True)

    def compute(self, inputs, outputs):
        """
        Execution.
        """
        outputs['y1'] = self.J1.dot(inputs['x1']) + self.J2.dot(inputs['x2']) + self.Jb.dot(inputs['bb'])

    def compute_jacvec_product(self, inputs, dinputs, doutputs, mode):
        """Returns the product of the incoming vector with the Jacobian."""

        if mode == 'fwd':
            if 'x1' in dinputs:
                doutputs['y1'] += self.J1.dot(dinputs['x1'])
            if 'x2' in dinputs:
                doutputs['y1'] += self.J2.dot(dinputs['x2'])
            if 'bb' in dinputs:
                doutputs['y1'] += self.Jb.dot(dinputs['bb'])

        elif mode == 'rev':
            if 'x1' in dinputs:
                dinputs['x1'] += self.J1.T.dot(doutputs['y1'])
            if 'x2' in dinputs:
                dinputs['x2'] += self.J2.T.dot(doutputs['y1'])
            if 'bb' in dinputs:
                dinputs['bb'] += self.Jb.T.dot(doutputs['y1'])

prob = om.Problem()
model = prob.model
model.add_subsystem('mycomp', ArrayCompMatrixFree(), promotes=['*'])

prob.setup()
prob.run_model()

data = prob.check_partials()

---------------------------------------
Component: ArrayCompMatrixFree 'mycomp'
---------------------------------------

  mycomp: 'y1' wrt (d)'bb'
     Forward Magnitude: 1.226664e+01
          Fd Magnitude: 1.226664e+01 (fd:forward)

    Absolute Error ([rev, fd] Dot Product Test) : 8.881784e-16
    Absolute Error ([rev, for] Dot Product Test) : 0.000000e+00

    Relative Error ([rev, fd] Dot Product Test) / Jfd : 7.240598e-17
    Relative Error ([rev, for] Dot Product Test) / Jfd : 0.000000e+00

    Directional Derivative (Jfor)
    [[  2.16595527]
     [ -5.08839636]
     [ -0.67806251]
     [-10.92829629]]

    Directional FD Derivative (Jfd)
    [[  2.16595527]
 [ -5.08839636]
 [ -0.67806251]
 [-10.92829629]]

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  mycomp: 'y1' wrt (d)'x1'
     Forward Magnitude: 1.153363e+01
          Fd Magnitude: 1.153363e+01 (fd:forward)

    Absolute Error ([rev, fd] Dot Product Test) : 0.000000e+00
    Absolute Error ([rev, for] Dot 

## Changing Global Settings For Whole Model

You can change the settings globally for all approximations used for all components. This is done by passing in a value for any of the following arguments:

| Name      | Description                                                                                    |
|-----------|------------------------------------------------------------------------------------------------|
| method    | Method for check: “fd” for finite difference, “cs” for complex step.                           |
| form      | Finite difference form for check, can be “forward”, “central”, or backward.                    |
| step      | Step size for finite difference check.                                                         |
| step_calc | When "abs", the step is absolute. A relative step can also be chosen with one of the values in table below.                                |
| minimum_step | Minimum allowable step when using one of the relative step_calc options. |

If you need to scale the finite difference step by the variable's magnitude, the following additional choices for "step_calc" are available:

| step_calc       | Step size is scaled by |
| :---            |    :----:                                       |
| "rel_avg"       | Average absolute value of the vector.           |
| "rel_element"   | Absolute value of each vector element.          |
| "rel_legacy"    | Norm of the vector.                             |
| "rel"           | Same as "rel__avg".                             |


```{Note}
The global check options take precedence over the ones defined on a component.
``` 

## Usage Examples

In [9]:
import openmdao.api as om
from openmdao.core.tests.test_check_partials import ParaboloidTricky
from openmdao.test_suite.components.paraboloid_mat_vec import ParaboloidMatVec

prob = om.Problem()

prob.model.add_subsystem('comp', ParaboloidTricky())
prob.model.add_subsystem('comp2', ParaboloidMatVec())

prob.model.connect('comp.f_xy', 'comp2.x')

prob.set_solver_print(level=0)

prob.setup()
prob.run_model()

prob.check_partials(step=1e-2, compact_print=True)

----------------------------------
Component: ParaboloidTricky 'comp'
----------------------------------

+-----------------+------------------+-------------+----------+-------------+-------------+------------+------------+-------------+------------+------------+------------+
| of '<variable>' | wrt '<variable>' |    fwd mag. | rev mag. |  check mag. |  a(fwd-chk) | a(rev-chk) | a(fwd-rev) |  r(fwd-chk) | r(rev-chk) | r(fwd-rev) | error desc |
+=================+==================+=============+==========+=============+=============+============+============+=============+============+============+============+
| 'f_xy'          | 'x'              |  6.0000e-07 | n/a      |  6.0000e-07 |  4.9644e-14 | n/a        | n/a        |  8.2740e-08 | n/a        | n/a        |            |
+-----------------+------------------+-------------+----------+-------------+-------------+------------+------------+-------------+------------+------------+------------+
| 'f_xy'          | 'y'              | 

{'comp': {('f_xy', 'x'): {'J_fwd': array([[-6.e-07]]),
   'J_fd': array([[-6.0000005e-07]]),
   'abs error': ErrorTuple(forward=4.964422262660536e-14, reverse=None, forward_reverse=None),
   'rel error': ErrorTuple(forward=8.274036419837383e-08, reverse=None, forward_reverse=None),
   'magnitude': MagnitudeTuple(forward=6e-07, reverse=None, fd=6.000000496442226e-07)},
  ('f_xy', 'y'): {'J_fwd': array([[8.e-07]]),
   'J_fd': array([[8.00000066e-07]]),
   'abs error': ErrorTuple(forward=6.619229683547381e-14, reverse=None, forward_reverse=None),
   'rel error': ErrorTuple(forward=8.274036419837383e-08, reverse=None, forward_reverse=None),
   'magnitude': MagnitudeTuple(forward=8e-07, reverse=None, fd=8.000000661922968e-07)}},
 'comp2': {('f_xy', 'x'): {'J_fwd': array([[38.]]),
   'J_rev': array([[38.]]),
   'J_fd': array([[38.01]]),
   'abs error': ErrorTuple(forward=0.010000000008403731, reverse=0.010000000008403731, forward_reverse=0.0),
   'rel error': ErrorTuple(forward=0.00026308866

Here is an example where we check our partials using complex step.

```{Note}
You need to set `force_alloc_complex` to True during setup to utilize complex step during a check.
```

In [10]:
import openmdao.api as om
from openmdao.core.tests.test_check_partials import ParaboloidTricky
from openmdao.test_suite.components.paraboloid_mat_vec import ParaboloidMatVec

prob = om.Problem()

prob.model.add_subsystem('comp', ParaboloidTricky())
prob.model.add_subsystem('comp2', ParaboloidMatVec())

prob.model.connect('comp.f_xy', 'comp2.x')

prob.set_solver_print(level=0)

prob.setup(force_alloc_complex=True)
prob.run_model()

prob.check_partials(method='cs', compact_print=True)

----------------------------------
Component: ParaboloidTricky 'comp'
----------------------------------

+-----------------+------------------+-------------+----------+-------------+-------------+------------+------------+-------------+------------+------------+------------+
| of '<variable>' | wrt '<variable>' |    fwd mag. | rev mag. |  check mag. |  a(fwd-chk) | a(rev-chk) | a(fwd-rev) |  r(fwd-chk) | r(rev-chk) | r(fwd-rev) | error desc |
+=================+==================+=============+==========+=============+=============+============+============+=============+============+============+============+
| 'f_xy'          | 'x'              |  6.0000e-07 | n/a      |  6.0000e-07 |  0.0000e+00 | n/a        | n/a        |  0.0000e+00 | n/a        | n/a        |            |
+-----------------+------------------+-------------+----------+-------------+-------------+------------+------------+-------------+------------+------------+------------+
| 'f_xy'          | 'y'              | 

{'comp': {('f_xy', 'x'): {'J_fwd': array([[-6.e-07]]),
   'J_fd': array([[-6.e-07]]),
   'abs error': ErrorTuple(forward=0.0, reverse=None, forward_reverse=None),
   'rel error': ErrorTuple(forward=0.0, reverse=None, forward_reverse=None),
   'magnitude': MagnitudeTuple(forward=6e-07, reverse=None, fd=6e-07)},
  ('f_xy', 'y'): {'J_fwd': array([[8.e-07]]),
   'J_fd': array([[8.e-07]]),
   'abs error': ErrorTuple(forward=1.0587911840678754e-22, reverse=None, forward_reverse=None),
   'rel error': ErrorTuple(forward=1.3234889800848445e-16, reverse=None, forward_reverse=None),
   'magnitude': MagnitudeTuple(forward=8e-07, reverse=None, fd=7.999999999999999e-07)}},
 'comp2': {('f_xy', 'x'): {'J_fwd': array([[38.]]),
   'J_rev': array([[38.]]),
   'J_fd': array([[38.]]),
   'abs error': ErrorTuple(forward=0.0, reverse=0.0, forward_reverse=0.0),
   'rel error': ErrorTuple(forward=0.0, reverse=0.0, forward_reverse=0.0),
   'magnitude': MagnitudeTuple(forward=38.0, reverse=38.0, fd=38.0)},
  ('

In this example, we check our partials with finite difference, but we use central differencing for more accuracy.

In [11]:
import openmdao.api as om
from openmdao.core.tests.test_check_partials import ParaboloidTricky
from openmdao.test_suite.components.paraboloid_mat_vec import ParaboloidMatVec

prob = om.Problem()

prob.model.add_subsystem('comp', ParaboloidTricky())
prob.model.add_subsystem('comp2', ParaboloidMatVec())

prob.model.connect('comp.f_xy', 'comp2.x')

prob.set_solver_print(level=0)

prob.setup()
prob.run_model()

prob.check_partials(form='central', compact_print=True)

----------------------------------
Component: ParaboloidTricky 'comp'
----------------------------------

+-----------------+------------------+-------------+----------+-------------+-------------+------------+------------+-------------+------------+------------+------------+
| of '<variable>' | wrt '<variable>' |    fwd mag. | rev mag. |  check mag. |  a(fwd-chk) | a(rev-chk) | a(fwd-rev) |  r(fwd-chk) | r(rev-chk) | r(fwd-rev) | error desc |
+=================+==================+=============+==========+=============+=============+============+============+=============+============+============+============+
| 'f_xy'          | 'x'              |  6.0000e-07 | n/a      |  5.9863e-07 |  1.3677e-09 | n/a        | n/a        |  2.2848e-03 | n/a        | n/a        |  >REL_TOL  |
+-----------------+------------------+-------------+----------+-------------+-------------+------------+------------+-------------+------------+------------+------------+
| 'f_xy'          | 'y'              | 

{'comp': {('f_xy', 'x'): {'J_fwd': array([[-6.e-07]]),
   'J_fd': array([[-5.98632255e-07]]),
   'abs error': ErrorTuple(forward=1.3677451221155663e-09, reverse=None, forward_reverse=None),
   'rel error': ErrorTuple(forward=0.0022847835394278477, reverse=None, forward_reverse=None),
   'magnitude': MagnitudeTuple(forward=6e-07, reverse=None, fd=5.986322548778844e-07)},
  ('f_xy', 'y'): {'J_fwd': array([[8.e-07]]),
   'J_fd': array([[8.01136935e-07]]),
   'abs error': ErrorTuple(forward=1.1369345695129958e-09, reverse=None, forward_reverse=None),
   'rel error': ErrorTuple(forward=0.0014191513590918411, reverse=None, forward_reverse=None),
   'magnitude': MagnitudeTuple(forward=8e-07, reverse=None, fd=8.01136934569513e-07)}},
 'comp2': {('f_xy', 'x'): {'J_fwd': array([[38.]]),
   'J_rev': array([[38.]]),
   'J_fd': array([[38.00000005]]),
   'abs error': ErrorTuple(forward=4.616777005139738e-08, reverse=4.616777005139738e-08, forward_reverse=0.0),
   'rel error': ErrorTuple(forward=1.2

In this example, we use a relative step-size. This is sometimes needed for casese where an input variable's value can be in a wide range of orders of magnitude, and we don't want the step size to become to small or large for it.

In [12]:
import openmdao.api as om
from openmdao.core.tests.test_check_partials import ParaboloidTricky

prob = om.Problem()

prob.model.add_subsystem('comp', ParaboloidTricky())

prob.set_solver_print(level=0)

prob.setup()
prob.run_model()

prob.check_partials(step_calc='rel', compact_print=True)

----------------------------------
Component: ParaboloidTricky 'comp'
----------------------------------

+-----------------+------------------+-------------+-------------+-------------+-------------+------------+
| of '<variable>' | wrt '<variable>' |   calc mag. |  check mag. |  a(cal-chk) |  r(cal-chk) | error desc |
+=================+==================+=============+=============+=============+=============+============+
| 'f_xy'          | 'x'              |  6.0000e-07 |  0.0000e+00 |  6.0000e-07 |  1.0000e+00 |  >REL_TOL  |
+-----------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'f_xy'          | 'y'              |  8.0000e-07 |  0.0000e+00 |  8.0000e-07 |  1.0000e+00 |  >REL_TOL  |
+-----------------+------------------+-------------+-------------+-------------+-------------+------------+

#################################################################
Sub Jacobian with Largest Relative Error: ParaboloidTricky 'comp'
#####

{'comp': {('f_xy', 'x'): {'J_fwd': array([[-6.e-07]]),
   'J_fd': array([[0.]]),
   'abs error': ErrorTuple(forward=6e-07, reverse=None, forward_reverse=None),
   'rel error': ErrorTuple(forward=1.0, reverse=None, forward_reverse=None),
   'magnitude': MagnitudeTuple(forward=6e-07, reverse=None, fd=0.0)},
  ('f_xy', 'y'): {'J_fwd': array([[8.e-07]]),
   'J_fd': array([[0.]]),
   'abs error': ErrorTuple(forward=8e-07, reverse=None, forward_reverse=None),
   'rel error': ErrorTuple(forward=1.0, reverse=None, forward_reverse=None),
   'magnitude': MagnitudeTuple(forward=8e-07, reverse=None, fd=0.0)}}}

Finally, in this example, we have a vector input whose elements differ by several orders of magnitude, and whose middle element is sometimes zero.  If you try to scale the step size by a variable that is zero, you end up with a step size equal to zero, which causes division by zero during computation.  To prevent this, OpenMDAO defines a minimum step size of 1e-12. You can change this value by setting the `minimum_step` argument to a new value whenever you set the `step_calc` argument. Here, we also use the 'rel_element' step_calc so that each element computes its own step size relative to the magnitude of that single element.

In [13]:
import numpy as np

import openmdao.api as om


class FDComp(om.ExplicitComponent):

    def initialize(self):
        self.options.declare('vec_size', types=int, default=1)

    def setup(self):
        nn = self.options['vec_size']

        self.add_input('x_element', np.ones((nn, )))
        self.add_output('y', np.ones((nn, )))

    def setup_partials(self):
        self.declare_partials('*', 'x_element')

        self.set_check_partial_options('x_element', method='fd', step_calc='rel_element', minimum_step=1e-15)

    def compute(self, inputs, outputs):
        x = inputs['x_element']
        outputs['y'] = 0.5 * x ** 2

    def compute_partials(self, inputs, partials):
        x = inputs['x_element']
        partials['y', 'x_element'] = np.diag(x)


prob = om.Problem()
model = prob.model

model.add_subsystem('comp', FDComp(vec_size=3))

prob.setup(force_alloc_complex=True)

x = np.array([1e10, 0.0, 1e-10])
prob.set_val('comp.x_element', x)

prob.run_model()

totals = prob.check_partials()

------------------------
Component: FDComp 'comp'
------------------------

  comp: 'y' wrt 'x_element'
     Forward Magnitude: 1.000000e+10
          Fd Magnitude: 1.000001e+10 (fd:forward)

    Absolute Error (Jfor - Jfd) : 5.000397e+03 *

    Relative Error (Jfor - Jfd) / Jfd : 5.000394e-07

    Raw Forward Derivative (Jfor)
    [[1.e+10 0.e+00 0.e+00]
     [0.e+00 0.e+00 0.e+00]
     [0.e+00 0.e+00 1.e-10]]

    Raw FD Derivative (Jfd)
    [[1.0000005e+10 0.0000000e+00 0.0000000e+00]
     [0.0000000e+00 5.0000000e-16 0.0000000e+00]
     [0.0000000e+00 0.0000000e+00 1.0000050e-10]]

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


In [14]:
from openmdao.utils.assert_utils import assert_near_equal
assert_near_equal(totals['comp']['y', 'x_element']['J_fd'][0][0], x[0], 1e-5)
assert_near_equal(totals['comp']['y', 'x_element']['J_fd'][1][1], x[1], 1e-5)
assert_near_equal(totals['comp']['y', 'x_element']['J_fd'][2][2], x[2], 1e-5)

4.9999963174089565e-06